version: '3.8'

services:
  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8003:8003"
    depends_on:
      - database

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    ports:
      - "8004:8004"
    environment:
      - BACKEND_URL=http://backend:8003
    depends_on:
      - backend

  database:
    image: mariadb:11.7.2-ubi9
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=biar
      - MYSQL_DATABASE=db_progetto
      - MYSQL_USER=user
      - MYSQL_PASSWORD=biar
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mariadb_data: 